/**
 * Block registry: default attributes and metadata per block type.
 * Single source of truth for builder UI and renderer.
 */

import type { BlockType } from './types.js';

export interface BlockDefinition {
  type: BlockType;
  label: string;
  category: 'text' | 'media' | 'design' | 'layout' | 'store' | 'form';
  defaultAttributes: Record<string, unknown>;
  /** For SEO: which HTML tag to use (e.g. heading level). */
  semanticTag?: string;
}

export const BLOCK_REGISTRY: Record<BlockType, BlockDefinition> = {
  'core/box': {
    type: 'core/box',
    label: 'Box',
    category: 'text',
    defaultAttributes: { fullBleed: false },
    semanticTag: 'div',
  },
  'core/paragraph': {
    type: 'core/paragraph',
    label: 'Paragraph',
    category: 'text',
    defaultAttributes: { content: '', fontFamily: '', textColor: '', fontSize: '', fontWeight: '', fontStyle: '', textAlign: 'left', verticalAlign: 'center', fullBleed: false },
    semanticTag: 'p',
  },
  'core/heading': {
    type: 'core/heading',
    label: 'Heading',
    category: 'text',
    defaultAttributes: { content: '', level: 2, fontFamily: '', textColor: '', fontSize: '', fontWeight: '', fontStyle: '', textAlign: 'left', verticalAlign: 'center', fullBleed: false },
    semanticTag: 'h2',
  },
  'core/image': {
    type: 'core/image',
    label: 'Image',
    category: 'media',
    defaultAttributes: { url: '', alt: '', caption: '', width: 100, captionFontFamily: '', captionTextColor: '', captionFontSize: '', captionFontWeight: '', captionFontStyle: '', fullBleed: false },
    semanticTag: 'figure',
  },
  'core/button': {
    type: 'core/button',
    label: 'Button',
    category: 'design',
    defaultAttributes: {
      text: 'Click me',
      url: '#',
      openInNewTab: false,
      fontFamily: '',
      textColor: '',
      fontSize: '',
      fontWeight: '',
      fontStyle: '',
      backgroundColor: '',
      borderRadius: '',
      padding: '',
      fullBleed: false,
    },
  },
  'core/columns': {
    type: 'core/columns',
    label: 'Columns',
    category: 'layout',
    defaultAttributes: { columns: 2, columnWidths: [50, 50], fullBleed: false },
    semanticTag: 'section',
  },
  'core/column': {
    type: 'core/column',
    label: 'Column',
    category: 'layout',
    defaultAttributes: { width: undefined, fullBleed: false },
  },
  'core/hero': {
    type: 'core/hero',
    label: 'Hero',
    category: 'design',
    defaultAttributes: {
      title: '',
      subtitle: '',
      backgroundImage: '',
      ctaText: '',
      ctaUrl: '#',
      fontFamily: '',
      textColor: '',
      titleFontFamily: '',
      titleTextColor: '',
      titleFontSize: '',
      titleFontWeight: '',
      titleFontStyle: '',
      subtitleFontFamily: '',
      subtitleTextColor: '',
      subtitleFontSize: '',
      subtitleFontWeight: '',
      subtitleFontStyle: '',
      ctaBackgroundColor: '',
      ctaBorderRadius: '',
      ctaPadding: '',
      ctaTextColor: '',
      ctaFontFamily: '',
      ctaFontSize: '',
      ctaFontWeight: '',
      ctaFontStyle: '',
      heroBackgroundColor: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'core/spacer': {
    type: 'core/spacer',
    label: 'Spacer',
    category: 'design',
    defaultAttributes: { height: 40, fullBleed: false },
  },
  'core/divider': {
    type: 'core/divider',
    label: 'Divider',
    category: 'design',
    defaultAttributes: { fullBleed: false },
    semanticTag: 'hr',
  },
  'core/list': {
    type: 'core/list',
    label: 'List',
    category: 'text',
    defaultAttributes: { items: [], ordered: false, fontFamily: '', textColor: '', fontSize: '', fontWeight: '', fontStyle: '', fullBleed: false },
    semanticTag: 'ul',
  },
  'core/custom': {
    type: 'core/custom',
    label: 'Custom Element',
    category: 'design',
    defaultAttributes: {
      html: '<div class="p-6 bg-gray-100 dark:bg-gray-800 rounded-lg">\n  <h3 class="text-xl font-semibold mb-2">Your custom block</h3>\n  <p class="text-gray-600 dark:text-gray-400">Paste HTML, CSS, and JavaScript to build custom components.</p>\n</div>',
      css: '',
      script: '',
      wrapperClasses: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'core/form': {
    type: 'core/form',
    label: 'Form',
    category: 'form',
    defaultAttributes: {
      title: 'Contact us',
      submitButtonText: 'Submit',
      submitScript: '/* Run on submit. formEl = form element, formData = FormData object */\nformEl.addEventListener("submit", (e) => {\n  e.preventDefault();\n  const data = new FormData(formEl);\n  console.log(Object.fromEntries(data));\n});',
      fullBleed: false,
    },
    semanticTag: 'form',
  },
  'core/form-input': {
    type: 'core/form-input',
    label: 'Form Input',
    category: 'form',
    defaultAttributes: {
      label: 'Field',
      inputType: 'text',
      placeholder: '',
      required: false,
      name: '',
    },
  },
  'core/form-select': {
    type: 'core/form-select',
    label: 'Form Select',
    category: 'form',
    defaultAttributes: {
      label: 'Choose',
      options: [{ value: 'option1', label: 'Option 1' }, { value: 'option2', label: 'Option 2' }],
      required: false,
      name: '',
    },
  },
  'core/form-textarea': {
    type: 'core/form-textarea',
    label: 'Form Textarea',
    category: 'form',
    defaultAttributes: {
      label: 'Message',
      placeholder: '',
      required: false,
      name: '',
      rows: 4,
    },
  },
  'core/quote': {
    type: 'core/quote',
    label: 'Quote',
    category: 'text',
    defaultAttributes: {
      content: '',
      citation: '',
      fontFamily: '',
      textColor: '',
      fontSize: '',
      fontWeight: '',
      fontStyle: '',
      citationFontFamily: '',
      citationTextColor: '',
      citationFontSize: '',
      citationFontWeight: '',
      citationFontStyle: '',
      fullBleed: false,
    },
    semanticTag: 'blockquote',
  },
  'store/product-grid': {
    type: 'store/product-grid',
    label: 'Product Grid',
    category: 'store',
    defaultAttributes: {
      title: 'Products',
      limit: 12,
      collectionId: '',
      apiEndpoint: '/v1/products',
      fontFamily: '',
      textColor: '',
      titleFontSize: '',
      titleFontWeight: '',
      titleFontStyle: '',
      buttonBackgroundColor: '',
      buttonColor: '',
      buttonFontFamily: '',
      buttonFontSize: '',
      buttonFontWeight: '',
      buttonFontStyle: '',
      buttonBorderRadius: '',
      buttonPadding: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'store/collection-list': {
    type: 'store/collection-list',
    label: 'Collection List',
    category: 'store',
    defaultAttributes: {
      title: 'Collections',
      apiEndpoint: '/collections',
      fontFamily: '',
      textColor: '',
      titleFontSize: '',
      titleFontWeight: '',
      titleFontStyle: '',
      buttonBackgroundColor: '',
      buttonColor: '',
      buttonFontFamily: '',
      buttonFontSize: '',
      buttonFontWeight: '',
      buttonFontStyle: '',
      buttonBorderRadius: '',
      buttonPadding: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'store/newsletter': {
    type: 'store/newsletter',
    label: 'Newsletter Signup',
    category: 'store',
    defaultAttributes: {
      title: 'Join our newsletter',
      subtitle: 'Get 10% off your first order. No spam, unsubscribe anytime.',
      buttonText: 'Subscribe',
      fontFamily: '',
      textColor: '',
      titleFontSize: '',
      titleFontWeight: '',
      titleFontStyle: '',
      buttonBackgroundColor: '',
      buttonColor: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'store/promo-banner': {
    type: 'store/promo-banner',
    label: 'Promo Banner',
    category: 'store',
    defaultAttributes: {
      text: 'Free shipping on orders over $50',
      backgroundColor: '',
      textColor: '',
      fontFamily: '',
      fontSize: '',
      fullBleed: false,
    },
    semanticTag: 'aside',
  },
  'store/testimonials': {
    type: 'store/testimonials',
    label: 'Testimonials',
    category: 'store',
    defaultAttributes: {
      title: 'What our customers say',
      items: [
        { quote: 'Amazing quality and fast shipping!', author: 'Sarah M.', rating: 5 },
        { quote: 'Best purchase I\'ve made this year.', author: 'James K.', rating: 5 },
        { quote: 'Will definitely order again.', author: 'Emma L.', rating: 5 },
      ],
      fontFamily: '',
      textColor: '',
      titleFontSize: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
  'store/trust-badges': {
    type: 'store/trust-badges',
    label: 'Trust Badges',
    category: 'store',
    defaultAttributes: {
      items: [
        { icon: '🚚', text: 'Free shipping' },
        { icon: '🔒', text: 'Secure payment' },
        { icon: '↩️', text: 'Easy returns' },
        { icon: '💬', text: '24/7 support' },
      ],
      fontFamily: '',
      textColor: '',
      fontSize: '',
      fullBleed: false,
    },
    semanticTag: 'section',
  },
};

export function getBlockDefinition(type: BlockType): BlockDefinition {
  const def = BLOCK_REGISTRY[type];
  if (!def) throw new Error(`Unknown block type: ${type}`);
  return def;
}

export function getBlocksByCategory(category: BlockDefinition['category']): BlockDefinition[] {
  return Object.values(BLOCK_REGISTRY).filter((b) => b.category === category);
}
